version: "3"

services:
  webserver:
    build: 
      context: ./docker/back-end
    container_name: webserver
    restart: 'always'
    ports:
      - 80:80
      - 443:443
    links: 
      - database
    volumes: 
      - ./www:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
  database:
    build:
      context: ./docker/mysql
    container_name: database
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}