version: "3.4"

services:
  nginx.financeira-backend.dev:
    container_name: nginx.financeira-backend.dev
    image: nginx:1.20
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bubble
    depends_on:
      - app.financeira-backend.dev
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  app.financeira-backend.dev:
    container_name: app.financeira-backend.dev
    build:
      context: .
      dockerfile: ./docker/back-end/Dockerfile
      args:
        APP_STAGE: 'dev'
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - bubble

  database:
    build:
      context: ./docker/mysql
    container_name: database
    restart: 'always'
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data/mysql:/var/lib/mysql
      - ./docker/mysql/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  zookeeper:
    container_name: zookeper.financeira-backend.dev
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka.financeira-backend.dev
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    container_name: kafdrop.financeira-backend.dev
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

networks:
  broker-kafka:
    driver: bridge
  bubble:
    external: true
